# NOTE: update this with your service name
service: pokemon-wish-list-api

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: prod
  region: us-east-1

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  want:
    handler: want.main
    events:
      - http:
          path: want
          method: post
          cors: true
          authorizer: aws_iam
  got:
    handler: got.main
    events:
      - http:
          path: got
          method: post
          cors: true
          authorizer: aws_iam
  query:
    handler: query.main
    events:
      - http:
          path: query
          method: get
          cors: true
          authorizer: aws_iam
